name: e_purna
description: >
  e-Purna — Register people, list products/services, and grow your business.
  

publish_to: "none" # This is a private project; don't publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For iOS icons and consistency with Material widgets
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app/icon_epurna.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app/icon_epurna.png"

flutter:

  uses-material-design: true

  # Register all assets folders here:
  assets:
    - assets/icons/homepage/
    # If you have more images later, add:
    # - assets/images/
    # - assets/fonts/
